[package]
name = "cluMultThreading"
version = "0.1.1"
authors = ["Денис Котляров <denis2005991@gmail.com>"]

[dependencies]
num_cpus = "1.8.0"
enclose = "0.1.2"
cluLog = {git = "https://github.com/clucompany/cluLog"}

